[libraries]
androidPlugin = "com.android.tools.build:gradle:8.6.1"
gradleMavenPublishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.29.0"
spotlessPlugin = "com.diffplug.spotless:spotless-plugin-gradle:6.25.0"

googleJavaFormat = "com.google.googlejavaformat:google-java-format:1.23.0"
